name: "Pipeline CICD"
on:
  push: # solo ejecuta el pipeline cuando se hace un commit a esta rama
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint: # name of the job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # ahora tengo el codigo en la pipeline
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install ruff
      - name: Lint the project
        run: ruff check --output-format=github
