name: "Pipeline CICD"
on:
  push: # solo ejecuta el pipeline cuando se hace un commit a esta rama
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test: # ahora se va a ejecutar para todas las combinaciones de python y os
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
      os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }} # ahora se va a ejecutar para todas las combinaciones de python y os
    steps:
      - uses: actions/checkout@v4 # ahora tengo el codigo en la pipeline
      - name: Setup Python ${{ matrix.python-version }}
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Test the project
        run: python -m pytest
